#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 25 17:17:05 2020

@author: macbookair2013
"""

import scipy as sp
from scipy.integrate import odeint
import matplotlib.pylab as plt

def bala(z,t):
    zp = sp.zeros(4)
    zp[0] = z[2]
    zp[1] = z[3]
    v = z[2:4]
    v[0]=v[0]-V
    v2 = sp.dot(v,v)
    vnorm = sp.sqrt(v2)
    FD = -CD * v2 *(v/vnorm)
    zp[2] = FD[0]/m
    zp[3] = FD[1]/m-g
    
    return zp


cm=0.01
inch=2.54*cm
g=9.81   

#coeficiente de arrastre
ro=1.225     
cd=0.47
D=8.5*inch
r=D/2
A=sp.pi*r**2
CD=0.5*ro*cd*A

#masa
m=15 #kg
#viento

V1= [0.,10.,20.]  #m/s
for V in V1:
    t = sp.linspace(0,30,1001)
    #Parte en el origen

    vi=100*1000./3600. #600 km/h
    z0 = sp.array([0,0,vi,vi,])

    sol = odeint(bala,z0,t)

    x=sol[:,0]
    y=sol[:,1]
    
    plt.ylim(0,50)
    plt.xlim(0,150)
    plt.plot(x,y)

plt.title("Trayectoria para distintos vientos")
plt.xlabel("X (m)")
plt.ylabel("Y (m)")
plt.grid(True)
plt.legend(["V = 0 m/s", "V = 10 m/s", "V = 20 m/s"])    
plt.figure()
plt.show()

